Iter9
0loff/go_link_shortener pull request #10
Opened 2023-10-29 19:37 UTC by 0loff

2023-11-02 21:10 UTC, vovean requested changes

2023-11-02 21:10 UTC, vovean commented on internal/handlers/handlers.go
> +		logger.Log.Debug("Cannot decode request JSON body", zap.Error(err))
Error

2023-11-02 21:10 UTC, vovean commented on internal/handlers/handlers.go
> +
местами заметил, что ставишь лишние строки после объявления функции

2023-11-02 21:10 UTC, vovean commented on internal/storage/storage.go
> +	ls.mu.Unlock()
давай через defer

2023-11-02 21:10 UTC, vovean commented on internal/storage/storageFileService.go
> +	return p.encoder.Encode(&entry)
хм, ты принимаешь указатель и здесь берешь еще раз указатель?? Т е указатель от указателя?

2023-11-02 21:10 UTC, vovean commented on internal/storage/storageFileService.go
> +	if err := c.decoder.Decode(&entry); err != nil {
тут тоже указатель на указатель

2023-11-03 02:50 UTC, 0loff commented on internal/handlers/handlers.go
> +		logger.Log.Debug("Cannot decode request JSON body", zap.Error(err))
Здесь и ниже уровень логирования изменен на Error.

2023-11-03 02:52 UTC, 0loff commented on internal/handlers/handlers.go
> +
Спасибо. Буду внимательнее к форматированию.

2023-11-03 02:52 UTC, 0loff commented on internal/storage/storage.go
> +	ls.mu.Unlock()
Изменено на вызов Unlock() через defer.

2023-11-03 02:53 UTC, 0loff commented on internal/storage/storageFileService.go
> +	return p.encoder.Encode(&entry)
Исправлено.

2023-11-03 02:53 UTC, 0loff commented on internal/storage/storageFileService.go
> +	if err := c.decoder.Decode(&entry); err != nil {
Исправлено.

2023-11-05 09:44 UTC, vovean approved these changes

2023-11-05 12:59 UTC, merged