Iter13
0loff/go_link_shortener pull request #14
Opened 2023-11-14 15:32 UTC by 0loff

2023-11-14 20:08 UTC, vovean requested changes

2023-11-14 20:08 UTC, vovean commented on cmd/shortener/main.go
> +	} else if config.StorageFile != "" {
не нужно делать ветку else, если в ветке if делается return

2023-11-14 20:08 UTC, vovean commented on internal/compressor/gzipHandler.go
> +	c.w.Header().Set("Content-Encoding", "gzip")
всегда? т е для 4хх и 5хх кодов тоже?

2023-11-14 20:08 UTC, vovean commented on pkg/handler/batchShortURLs.go
> +		log.Println(err)
а какой-нить статус ошибки указать клиенту?

2023-11-14 20:08 UTC, vovean commented on pkg/handler/batchShortURLs.go
> +		logger.Log.Error("Error encoding response ", zap.Error(err))
хм, в ошибках выше, например, при анмаршалинге json у тебя встроенны в гошку логер, а тут ты другой используешь. Давай везде один логгер выберем и будем использовать

2023-11-14 20:08 UTC, vovean commented on pkg/handler/createShortURL.go
> +		log.Println(err)
код ошибки

2023-11-14 20:08 UTC, vovean commented on pkg/handler/createShortURL.go
> +		statusHeader = http.StatusConflict
логируешь эту ошибку внутри сервиса?

2023-11-14 20:08 UTC, vovean commented on pkg/handler/createShortURLjson.go
> +		logger.Log.Error("Cannot decode request JSON body", zap.Error(err))
вооот, отлично. Тут и логгер zap, и код ошибки клиенту указывается ура ура. Вот так нужно во всех остальных хендлерах сделать, где ошибку обрабатываешь и делаешь return

2023-11-14 20:08 UTC, vovean commented on pkg/handler/getShortURL.go
> +		return
есть такое понятие как happy path - эта часть кода, которая описывает успешный сценарий, успешную ветку выполнения кода, без ошибок. Хорошей практикой является делать так, чтобы основная ветка твой функции и была happy path. У тебя здесь получается, что happy path - какая то ветка функции, а не ее основная ветка, основной флоу. Давай поменяем.

Т е тут тебе надо сделать, чтобы в ифе проверялся бы кейс, когда линк пустой, а в главной ветке функции был бы успешный кейс с редиректом. Это будет консистентно с тем, как ты делаешь в остальных функциях. Там же в ифах обрабатываются ошибки, а не успешные кейсы

2023-11-14 20:08 UTC, vovean commented on pkg/handler/pingDBConnect.go
> +		w.WriteHeader(http.StatusInternalServerError)
вот тут return забыл. Без него ты выйдешь из ифа и перепишешь записанный 500 на 200

2023-11-14 20:08 UTC, vovean commented on pkg/repository/dbRepository/repo.go
> +	defer cancel()
лучше принимать контекст снаружи, как параметр функции. Тогда ты сможешь заюзать контекст из запроса. Это нужно хотя бы, чтоб не потерять все значения, которые когда-то клали в контекст, например трейсы для Jaeger

2023-11-14 20:08 UTC, vovean commented on pkg/repository/dbRepository/repo.go
> +		return ""
ты просто сглатываешь ошибку сканирования? может хотя бы залогировать?

2023-11-14 20:08 UTC, vovean commented on pkg/repository/dbRepository/repo.go
> +	defer cancel()
относится ко всем методам

2023-11-14 20:08 UTC, vovean commented on pkg/repository/dbRepository/repo.go
> +	return shortURL, err
а зачем ты примаешь shortURL и потом его же возвращаешь, никак не меняя?

2023-11-14 20:08 UTC, vovean commented on pkg/repository/dbRepository/repo.go
> +			err = repository.ErrConflict
можно сразу делать return, а не тянуть эту переменную до самого низа функции

2023-11-14 20:08 UTC, vovean commented on pkg/repository/dbRepository/repo.go
> +		_, err := stmt.ExecContext(ctx, u.ShortURL, u.OriginalURL)
ходить в базу в цикле это айайай, очень неэффективно :(((((

сделай, например, один большой жирный инсерт и туда передавай все урлы и тогда сможешь сделать все 1 запросом

А так у тебя 100500 сетевых походов

2023-11-14 20:08 UTC, vovean commented on pkg/repository/dbRepository/repo.go
> +		panic(err)
если ты кидаешь панику, то rollback не сработает

2023-11-14 20:08 UTC, vovean commented on pkg/service/service.go
> +		s.Repo.BatchInsertShortURLS(batchEntries)
а проверить, вставилось ли оно вообще? Может там вообще ошибка случилась

2023-11-17 05:28 UTC, 0loff commented on cmd/shortener/main.go
> +	} else if config.StorageFile != "" {
Убрал лишние else.

2023-11-17 05:30 UTC, 0loff commented on internal/compressor/gzipHandler.go
> +	c.w.Header().Set("Content-Encoding", "gzip")
Вернул условие, вынес установку заголовка на уровень handler'а ghb при условии передачи клиентом соответствующего заголовка.

2023-11-17 05:33 UTC, 0loff commented on pkg/handler/batchShortURLs.go
> +		log.Println(err)
Возвращаем статус Bad Request, логируем ошибку.

2023-11-17 05:35 UTC, 0loff commented on pkg/handler/batchShortURLs.go
> +		logger.Log.Error("Error encoding response ", zap.Error(err))
Изменил используемый логер во всех местах вызова.

2023-11-17 05:36 UTC, 0loff commented on pkg/handler/createShortURL.go
> +		log.Println(err)
+

2023-11-17 05:37 UTC, 0loff commented on pkg/handler/createShortURL.go
> +		statusHeader = http.StatusConflict
Да, теперь логируем ошибку на уровне сервиса.

2023-11-17 05:39 UTC, 0loff commented on pkg/handler/createShortURLjson.go
> +		logger.Log.Error("Cannot decode request JSON body", zap.Error(err))
Во всех хэндлерах при возникновении ошибок добавлено логиорвание.

2023-11-17 05:41 UTC, 0loff commented on pkg/handler/getShortURL.go
> +		return
Спасибо, возьму на заметку. Переделал.

2023-11-17 05:44 UTC, 0loff commented on pkg/handler/pingDBConnect.go
> +		w.WriteHeader(http.StatusInternalServerError)
Действительно. Добавил return.

2023-11-17 05:46 UTC, 0loff commented on pkg/repository/dbRepository/repo.go
> +	defer cancel()
Исправлено. Контекст передается их хэндлеров. Так же исправлен интерфейс, все репозитории, а так же тесты.

2023-11-17 05:49 UTC, 0loff commented on pkg/repository/dbRepository/repo.go
> +		return ""
Добавил логирование при вызове Scan в методах FindByID и FindByLink.

2023-11-17 05:50 UTC, 0loff commented on pkg/repository/dbRepository/repo.go
> +	return shortURL, err
Теперь в случае успешной вставки в БД возвращаем исходный ShortURL, в случае же получения ошибки - пустую строку.

2023-11-17 05:51 UTC, 0loff commented on pkg/repository/dbRepository/repo.go
> +			err = repository.ErrConflict
Делаем return после получения ошибки.

2023-11-17 05:53 UTC, 0loff commented on pkg/repository/dbRepository/repo.go
> +		_, err := stmt.ExecContext(ctx, u.ShortURL, u.OriginalURL)
Да, тут косяк. Полностью переделал метод. Теперь происходит множественная вставка единой транзакцией.

2023-11-17 05:54 UTC, 0loff commented on pkg/repository/dbRepository/repo.go
> +		panic(err)
Метод отрефакторен.

2023-11-17 05:55 UTC, 0loff commented on pkg/service/service.go
> +		s.Repo.BatchInsertShortURLS(batchEntries)
Логирую ошибку множественной вставки.

2023-11-21 19:01 UTC, vovean approved these changes

2023-11-22 03:42 UTC, merged