Iter18: Added simple documentation and some example
0loff/go_link_shortener pull request #19
Opened 2024-01-30 17:11 UTC by 0loff

2024-02-02 02:24 UTC, capsulated requested changes
- сортировка импортов ок
- документация ок
- бенчмарки ок

Проблема по тестам: 
```
--- FAIL: ExampleGetUserID (0.00s)
got:
token is expired by 40h40m10.811638s
want:
3462f28c-1c3a-457f-8849-c5216fbf9e16
FAIL
coverage: 17.6% of statements
FAIL    github.com/0loff/go_link_shortener/internal/auth        0.394s
ok      github.com/0loff/go_link_shortener/pkg/base62   0.570s  coverage: 0.0% of statements [no tests to run]
FAIL
```
Из-за этого не могу проверить тотальное покрытие тестами. Нужно пофиксить

Также, есть замечания по именам фалов: нейминг файлов должен быть в `snake_case`, а не в `camelCase` по рекомендациям коммьюнити (смотри нативные библиотеки go, а также популярные проекты, написанные на go)

Круто, что часть логики в `pkg`, часть в `internal`. По идее, хендлеры должны быть в internal, так как это внутренняя enterprise логика. А такие пакеты, как compressor и часть логики аунтификации вполне для pkg. Стратегия следующая: можно сравнить с выпускным gofermart  b повторяющийся функционал - явный претендент для переноса в pkg. И в следующим выпускном можно легко импортировать из git репозитория инкрементов

2024-02-02 02:24 UTC, capsulated commented on pkg/handler/batchShortURLs.go
Хендлеры из `internal` переностить в `pkg` для текущего проека - в принципе ок.

Но на практике, вот что посоветую: можно проанализировать инкременты и выпускной gofrtmart. Найти дублирующийся функционал и распределить его по пакетам. Именно этот функционал вынести в `pkg` и его можно импортировать, скажем, в следующем выпускном проекте. Это аналоги public/private для переменных, только в рамках пакета. То есть, всё что в internal - это private пакеты

2024-02-03 10:57 UTC, 0loff commented on pkg/handler/batchShortURLs.go
- Исправил ошибку при прохождении тестов в ExampleGetUserID, попутно переосмыслив подход к формированию токена авторизации с установкой uuid. Теперь можно проверить процент покрытия проекта тестами;
- По всему проекту изменил нейминг с ```camelCase``` на ```snake_case```;
- Провел анализ и начал разделение логики пакетов на общую и внутреннюю логику. Разделив ряд пакетов (в том числе compressor и часть логики аутентификации) и выделив общую логику вынес их в pkg. В перспективе при выполнении следующих инкрементов буду выносить данные пакеты в отдельные GitHub репозитория для повторного использования в существующем gophermart, а так же будущего выпускного проекта.

2024-02-05 19:58 UTC, capsulated commented on pkg/handler/batchShortURLs.go
Огонь!

2024-02-05 19:59 UTC, capsulated approved these changes
Класс! 👍

2024-02-07 16:04 UTC, merged