Iter5
0loff/go_link_shortener pull request #6
Opened 2023-10-08 15:26 UTC by 0loff

2023-10-10 21:01 UTC, vovean requested changes

2023-10-10 21:01 UTC, vovean commented on cmd/client/main.go
> +	endpoint := "http://127.0.0.1:8080"
было бы правильнее читать этот адрес из флага или переменной окружения

2023-10-10 21:01 UTC, vovean commented on cmd/client/main.go
> +	client := &http.Client{}
хорошей практикой было бы задать хотя бы значения для различных таймаутов

2023-10-10 21:01 UTC, vovean commented on cmd/shortener/config.go
> +type ConfigBuilder struct {
отличное использование паттерна Builder!

2023-10-10 21:01 UTC, vovean commented on cmd/shortener/config.go
> +func (cb ConfigBuilder) Build() Config {
а нужен ли отдельный метод Build, если все SetXXX методы и так возвращают актуальный конфиг?

2023-10-10 21:01 UTC, vovean commented on cmd/shortener/config.go
> +	return nil
зачем функция возвращает ошибку, если они всегда nil?

2023-10-10 21:01 UTC, vovean commented on cmd/shortener/main.go
> +var linkStorage = map[string]string{}
было бы хорошо использовать паттерн Repository и скрыть мапу за каким нить более абстрактным типом.

Это поможет в будущем, при интеграции другой БД совершить переезд без багов и с меньшим объемом переписанного кода

2023-10-10 21:01 UTC, vovean commented on cmd/shortener/main.go
> +		log.Fatal(err)
может не стоит сразу фаталить? Можно просто написать ошибку клиенту и сразу завершить выполнение метода через return

2023-10-10 21:01 UTC, vovean commented on cmd/shortener/main.go
> +	w.Write([]byte(config.ShortLinkHost + "/" + base64.RawStdEncoding.EncodeToString(body)))
операция кодирование в base64 относительно дорогая и тут ты ее делаешь второй раз с теми же данными, как на 26 строке. Может стоит вынести в переменную и делать кодирование всего 1 раз?

2023-10-10 21:01 UTC, vovean commented on cmd/shortener/main.go
> +	} else {
можно не писать else, когда внутри if делается return

2023-10-10 21:01 UTC, vovean commented on cmd/shortener/main_test.go
> +				expectedBody:   "http://localhost:8080/aHR0cHM6Ly9wcmFjdGljdW0ueWFuZGV4LnJ1Lw",
хехе, кажется, что твой "укорачиватель" ссылок сделал ее длиннее xD

2023-10-13 05:26 UTC, 0loff commented on cmd/client/main.go
> +	endpoint := "http://127.0.0.1:8080"
Это просто сохраненный пример из теоретической части - https://practicum.yandex.ru/learn/go-advanced/courses/fe725b51-a888-4c0a-809a-611a1ef8e2ba/sprints/139864/topics/6582b0e4-a277-4b6e-b492-a9b98681d530/lessons/a535ccde-9231-48a6-9ac2-ca7b8149c8bf/ (в самом конце, перед заданием 6/8). Решил сохранить на всякий случай. В ходе выполнения работы им не пользуюсь.

2023-10-13 05:28 UTC, 0loff commented on cmd/client/main.go
> +	client := &http.Client{}
[https://github.com/0loff/go_link_shortener/pull/6#discussion_r1357780363](Так же актульно для текушего комментария)

2023-10-13 05:33 UTC, 0loff commented on cmd/shortener/config.go
> +type ConfigBuilder struct {
Спасибо!

2023-10-13 05:40 UTC, 0loff commented on cmd/shortener/config.go
> +func (cb ConfigBuilder) Build() Config {
Методы SetXXX действительно работают с наполнением актуального конфига, работая при этом со структурой ConfigBuilder. Финальный Build выполняю для чистоты восприятия и разделения объектов Config и ConfigBuilder. Т.е. в ходе наполнения параметрами запуска, структура ConfigBuilder работает со структурой Config. А в финале с помощью вызова Build, возвращается чистая, не вложенная структура (объект) Config. Согласен, этого же можно добиться просто возвращая из ConfigBuilder cb.config. Однако на мой взгляд так выглядит чище.

2023-10-13 05:42 UTC, 0loff commented on cmd/shortener/config.go
> +	return nil
Лишний возврат ошибки. Убрал.

2023-10-13 05:43 UTC, 0loff commented on cmd/shortener/main.go
> +var linkStorage = map[string]string{}
Хорошее замечание. Вынес linkStorage в отдельную структуру.

2023-10-13 05:46 UTC, 0loff commented on cmd/shortener/main.go
> +		log.Fatal(err)
Справедливо. Довольно радикально фаталить сервер при не валидном body запроса. Изменил на отображение ошибки и возврат из функции.

2023-10-13 05:47 UTC, 0loff commented on cmd/shortener/main.go
> +	w.Write([]byte(config.ShortLinkHost + "/" + base64.RawStdEncoding.EncodeToString(body)))
Пересмотрел подход с созданием сокращенного URL. Больше не используется base64 кодирование, а так же процедура кодирования вызывается всего один раз.

2023-10-13 05:48 UTC, 0loff commented on cmd/shortener/main.go
> +	} else {
Убрал условие else.

2023-10-13 05:49 UTC, 0loff commented on cmd/shortener/main_test.go
> +				expectedBody:   "http://localhost:8080/aHR0cHM6Ly9wcmFjdGljdW0ueWFuZGV4LnJ1Lw",
Это в самом деле выглядит забавно) Полностью пересмотрел подход создания сокращенного URL. Теперь короче.

2023-10-14 11:30 UTC, vovean requested changes

2023-10-14 11:30 UTC, vovean commented on cmd/shortener/linkStorage.go
> +	linkEntries map[string]string
тут будет конкурентный доступ к мапе на запись и чтение. Такое поведение придет к фатальной ошибке в го, которая еще хуже паники, потому что такую ошибку даже recover() не поймает

Нужно добавить мьютекс

2023-10-16 03:23 UTC, 0loff commented on cmd/shortener/linkStorage.go
> +	linkEntries map[string]string
Добавлена блокировка обращений через запросы к структуре LinkStorageRepository с помощью Mutex.

2023-10-18 20:15 UTC, vovean approved these changes

2023-10-19 15:06 UTC, merged